services:
  - type: web
    name: nive-protocol
    runtime: python
    plan: free
    buildCommand: pip install -e .
    startCommand: python -m api.server
    healthCheckPath: /health
    envVars:
      - key: NIVE_REGISTRY_ADDRESS
        value: 0x4bee3427e9c85ec82a4925ccec3984c927d8385d
      - key: NIVE_TASK_MANAGER_ADDRESS
        value: 0xbc98de8ad6d9f2c29aa3208f527bcf6e3fb81245
      - key: NIVE_SETTLEMENT_ADDRESS
        value: 0xf9d81e2e6d54f3c199cf5edd7a5788f2c5b7be16
      - key: NIVE_BRIDGE_ADDRESS
        value: 0x94efa28ea5d85a9cffb6e1d772cb7359994c7206
      - key: NIVE_CORE_ADDRESS
        value: 0xf9d3dfc0b686cabaaa1389600aa1e14dff3fa54f
      - key: NIVE_RPC_URL
        sync: false
