// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import {IVerifier} from "../interfaces/IVerifier.sol";

/// @title NiveVerifier
/// @notice Concrete Groth16 verifier over the BN254 (alt_bn128) curve for the
///         Nive execution-proof circuit.
/// @dev Implements {IVerifier}. Verification runs entirely on the BN254
///      precompiles (ecAdd 0x06, ecMul 0x07, ecPairing 0x08) via `staticcall`
///      in a `view` function, so it is side-effect free and safe for the
///      {SettlementEngine} to call from a static frame.
///
///      One instance per circuit: the verification key is fixed at
///      construction. Deploy a fresh instance whenever a circuit is upgraded
///      and rotate via `SettlementEngine.setVerifier`.
///
///      Proof wire format — exactly 8 big-endian 32-byte words (256 bytes):
///        [0] pi_a.x        [1] pi_a.y                     G1 (little group)
///        [2] pi_b.x.im     [3] pi_b.x.re                  G2 x, EIP-197 order
///        [4] pi_b.y.im     [5] pi_b.y.re                  G2 y, EIP-197 order
///        [6] pi_c.x        [7] pi_c.y                     G1
///      NOTE: EIP-197 encodes Fp2 elements as (imaginary, real). snarkjs
///      serializes G2 as (real, imaginary) — swap the components when
///      submitting proofs generated by snarkjs/Circom.
///
///      Verification equation (standard Groth16):
///        e(-pi_a, pi_b) * e(vk.alpha, vk.beta) * e(pi_c, vk.delta)
///          * e(vk_x, vk.gamma) == 1
///      with vk_x = vk.IC[0] + sum(publicInputs[i] * vk.IC[i+1]).
///
///      `verifyProof` returns false (never reverts) on any malformed input:
///      wrong proof length, field-element overflow, off-curve/non-subgroup
///      points, or a failed pairing check. Public inputs are scalars mod r:
///      values >= r are reduced by EIP-196 scalar-multiplication semantics
///      (snarkjs/Gnark verifier behavior). This is deliberate — the engine
///      binds `publicInputs[0]` to the raw `uint256` task id, and keccak ids
///      exceed r most of the time, so rejecting them would brick settlement.
contract NiveVerifier is IVerifier {
    // ────────────────────────────────
    //  Errors
    // ────────────────────────────────

    error NiveVerifier__ZeroAlpha();
    error NiveVerifier__NoVerificationKey();

    // ────────────────────────────────
    //  Constants
    // ────────────────────────────────

    /// @dev BN254 base field modulus p.
    uint256 internal constant P =
        21888242871839275222246405745257275088696311157297823662689037894645226208583;

    /// @dev BN254 scalar field order r ( subgroup order ).
    uint256 internal constant R =
        21888242871839275222246405745257275088548364400416034343698204186575808495617;

    address internal constant PRECOMPILE_ADD = address(0x06);
    address internal constant PRECOMPILE_MUL = address(0x07);
    address internal constant PRECOMPILE_PAIRING = address(0x08);

    // ────────────────────────────────
    //  Types
    // ────────────────────────────────

    /// @dev Decoded proof words, EIP-197 wire order (see contract docs).
    struct ProofWords {
        uint256 ax;
        uint256 ay;
        uint256 bx0; // pi_b.x imaginary
        uint256 bx1; // pi_b.x real
        uint256 by0; // pi_b.y imaginary
        uint256 by1; // pi_b.y real
        uint256 cx;
        uint256 cy;
    }

    // ────────────────────────────────
    //  Verification key
    // ────────────────────────────────

    /// @dev Verification key points. Storage fixed-arrays (not immutables)
    ///      keep the pairing frame shallow; exposed via the alpha1/beta2/
    ///      gamma2/delta2 getters.
    uint256[2] private _alpha1;
    uint256[4] private _beta2;   // EIP-197 component order: (im, re)
    uint256[4] private _gamma2;  // EIP-197 component order: (im, re)
    uint256[4] private _delta2;  // EIP-197 component order: (im, re)

    /// @notice Input points: IC[0] is the constant term; IC[i+1] multiplies
    ///         publicInputs[i]. Length = number of public inputs + 1.
    uint256[] public icX;
    uint256[] public icY;

    /// @notice Number of public inputs this circuit's key commits to.
    uint256 public publicInputCount;

    // ────────────────────────────────
    //  Constructor
    // ────────────────────────────────

    constructor(
        uint256[2] memory alpha1,
        uint256[4] memory beta2,
        uint256[4] memory gamma2,
        uint256[4] memory delta2,
        uint256[2][] memory ic
    ) {
        if (ic.length == 0) revert NiveVerifier__NoVerificationKey();
        if (alpha1[0] == 0 && alpha1[1] == 0) revert NiveVerifier__ZeroAlpha();

        _alpha1 = alpha1;
        _beta2 = beta2;
        _gamma2 = gamma2;
        _delta2 = delta2;

        for (uint256 i = 0; i < ic.length; i++) {
            icX.push(ic[i][0]);
            icY.push(ic[i][1]);
        }
        publicInputCount = ic.length - 1;
    }

    // ────────────────────────────────
    //  Verification
    // ────────────────────────────────

    /// @inheritdoc IVerifier
    /// @dev Returns false instead of reverting on any malformed input so a
    ///      bad proof fails settlement with the engine's `InvalidProof`
    ///      error rather than an opaque revert.
    function verifyProof(
        bytes calldata proof,
        uint256[] calldata publicInputs
    ) external view override returns (bool valid) {
        // Exact 256-byte proof layout (8 words) — see contract docs.
        if (proof.length != 256) return false;

        // Proof must be for this circuit's key shape.
        if (publicInputs.length != publicInputCount) return false;

        ProofWords memory p = _decodeProof(proof);
        if (_coordinateOverflow(p)) return false;

        // vk_x = IC[0] + sum(IC[i+1] * publicInputs[i])  (G1).
        (uint256 vkx, uint256 vky) = _commitInputs(publicInputs);

        return _runPairing(p, vkx, vky);
    }

    /// @notice IC point for public input index `i` (as in the circuit witness).
    function icPoint(uint256 i) external view returns (uint256, uint256) {
        return (icX[i], icY[i]);
    }

    // ────────────────────────────────
    //  Internal
    // ────────────────────────────────

    function _decodeProof(bytes calldata proof)
        internal
        pure
        returns (ProofWords memory p)
    {
        p.ax = uint256(bytes32(proof[0:32]));
        p.ay = uint256(bytes32(proof[32:64]));
        p.bx0 = uint256(bytes32(proof[64:96]));
        p.bx1 = uint256(bytes32(proof[96:128]));
        p.by0 = uint256(bytes32(proof[128:160]));
        p.by1 = uint256(bytes32(proof[160:192]));
        p.cx = uint256(bytes32(proof[192:224]));
        p.cy = uint256(bytes32(proof[224:256]));
    }

    /// @dev All coordinates must be Fp elements (< p).
    function _coordinateOverflow(ProofWords memory p) internal pure returns (bool) {
        return p.ax >= P || p.ay >= P || p.cx >= P || p.cy >= P
            || p.bx0 >= P || p.bx1 >= P || p.by0 >= P || p.by1 >= P;
    }

    /// @dev MSM of the public inputs over the IC points: the circuit's
    ///      commitment to the statement being proven.
    function _commitInputs(uint256[] calldata publicInputs)
        internal
        view
        returns (uint256 vkx, uint256 vky)
    {
        (vkx, vky) = (icX[0], icY[0]);
        for (uint256 i = 0; i < publicInputs.length; i++) {
            (bool okMul, uint256 px, uint256 py) = _ecMul(icX[i + 1], icY[i + 1], publicInputs[i]);
            if (!okMul) return (0, 0);
            (bool okAdd, uint256 nx, uint256 ny) = _ecAdd(vkx, vky, px, py);
            if (!okAdd) return (0, 0);
            (vkx, vky) = (nx, ny);
        }
    }

    /// @notice Verification key, alpha1 (G1).
    function alpha1() external view returns (uint256[2] memory) {
        return _alpha1;
    }

    /// @notice Verification key, beta2 (G2, EIP-197 order).
    function beta2() external view returns (uint256[4] memory) {
        return _beta2;
    }

    /// @notice Verification key, gamma2 (G2, EIP-197 order).
    function gamma2() external view returns (uint256[4] memory) {
        return _gamma2;
    }

    /// @notice Verification key, delta2 (G2, EIP-197 order).
    function delta2() external view returns (uint256[4] memory) {
        return _delta2;
    }

    /// @dev Groth16 pairing check:
    ///      e(-pi_a, pi_b) · e(alpha, beta) · e(pi_c, delta) · e(vk_x, gamma) == 1
    /// @dev Assembly builds the 768-byte precompile input in free memory
    ///      (scratch, never freed) — keeps the frame far below the stack limit.
    ///      The pi_a negation is computed in Solidity from the audited `P`
    ///      constant (inlined hex literals here are a known foot-gun).
    function _runPairing(ProofWords memory p, uint256 vkx, uint256 vky)
        internal
        view
        returns (bool valid)
    {
        // (0, 0) from _commitInputs failure would be the G1 identity, not an
        // error signal — any real IC commit is a valid curve point, so
        // reject the identity here.
        if (vkx == 0 && vky == 0) return false;

        uint256[2] memory a1 = _alpha1;
        uint256[4] memory b2 = _beta2;
        uint256[4] memory d2 = _delta2;
        uint256[4] memory g2 = _gamma2;
        uint256 negAy = p.ay == 0 ? 0 : P - p.ay;

        assembly {
            let fptr := mload(0x40)
            // (-pi_a, pi_b): negate pi_a.y (negation of (x,y) is (x, p-y)).
            mstore(fptr, mload(p))                                  // pi_a.x
            mstore(add(fptr, 32), negAy)
            mstore(add(fptr, 64), mload(add(p, 64)))                // pi_b.x.im
            mstore(add(fptr, 96), mload(add(p, 96)))                // pi_b.x.re
            mstore(add(fptr, 128), mload(add(p, 128)))              // pi_b.y.im
            mstore(add(fptr, 160), mload(add(p, 160)))              // pi_b.y.re
            // (alpha, beta)
            mstore(add(fptr, 192), mload(a1))
            mstore(add(fptr, 224), mload(add(a1, 32)))
            mstore(add(fptr, 256), mload(b2))
            mstore(add(fptr, 288), mload(add(b2, 32)))
            mstore(add(fptr, 320), mload(add(b2, 64)))
            mstore(add(fptr, 352), mload(add(b2, 96)))
            // (pi_c, delta)
            mstore(add(fptr, 384), mload(add(p, 192)))              // pi_c.x
            mstore(add(fptr, 416), mload(add(p, 224)))              // pi_c.y
            mstore(add(fptr, 448), mload(d2))
            mstore(add(fptr, 480), mload(add(d2, 32)))
            mstore(add(fptr, 512), mload(add(d2, 64)))
            mstore(add(fptr, 544), mload(add(d2, 96)))
            // (vk_x, gamma)
            mstore(add(fptr, 576), vkx)
            mstore(add(fptr, 608), vky)
            mstore(add(fptr, 640), mload(g2))
            mstore(add(fptr, 672), mload(add(g2, 32)))
            mstore(add(fptr, 704), mload(add(g2, 64)))
            mstore(add(fptr, 736), mload(add(g2, 96)))

            let success := staticcall(gas(), 0x08, fptr, 768, fptr, 32)
            valid := and(success, eq(mload(fptr), 1))
        }
    }

    /// @dev Returns ok=false instead of reverting when the precompile rejects
    ///      the input (off-curve point), so malformed proofs fail settlement
    ///      with the engine's `InvalidProof` error, not an opaque revert.
    function _ecAdd(
        uint256 x1, uint256 y1,
        uint256 x2, uint256 y2
    ) internal view returns (bool ok, uint256 x3, uint256 y3) {
        bytes memory input = abi.encodePacked(x1, y1, x2, y2);
        (bool called, bytes memory out) = PRECOMPILE_ADD.staticcall(input);
        if (!called || out.length != 64) return (false, 0, 0);
        return (true, _readWord(out, 0), _readWord(out, 32));
    }

    function _ecMul(
        uint256 x, uint256 y, uint256 scalar
    ) internal view returns (bool ok, uint256 x2, uint256 y2) {
        bytes memory input = abi.encodePacked(x, y, scalar);
        (bool called, bytes memory out) = PRECOMPILE_MUL.staticcall(input);
        if (!called || out.length != 64) return (false, 0, 0);
        return (true, _readWord(out, 0), _readWord(out, 32));
    }

    /// @dev Reads the 32-byte word of `data` starting at byte `offset`.
    function _readWord(bytes memory data, uint256 offset)
        internal
        pure
        returns (uint256 word)
    {
        assembly {
            word := mload(add(data, add(32, offset)))
        }
    }
}
